version: '3.8'

services:
  gene-analytics:
    build: .
    container_name: gene_language_analytics
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
